version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    ports:
      - "5000:5000"
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    depends_on:
      - mongo

  mongo:
      image: mongo:8.0.3
      container_name: mongo_db
      volumes:
        - mongo_data:/data/db

volumes:
  mongo_data: